services:
  postgres:
    image: docker.io/postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
